(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 336,
	height: 280,
	fps: 60,
	color: "#FFFFFF",
	webfonts: {},
	manifest: [
		{src:"images/bg.jpg", id:"bg"},
		{src:"images/bot.png", id:"bot"},
		{src:"images/bottom.png", id:"bottom"},
		{src:"images/btn.jpg", id:"btn"},
		{src:"images/h1.png", id:"h1"},
		{src:"images/h2.png", id:"h2"},
		{src:"images/h3.png", id:"h3"},
		{src:"images/h4.png", id:"h4"},
		{src:"images/h5.png", id:"h5"},
		{src:"images/h6.png", id:"h6"},
		{src:"images/head.png", id:"head"},
		{src:"images/logo_b.png", id:"logo_b"},
		{src:"images/logo_w.png", id:"logo_w"},
		{src:"images/pat.jpg", id:"pat"},
		{src:"images/top.png", id:"top"}
	]
};



lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,280);


(lib.bot = function() {
	this.initialize(img.bot);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,79,266);


(lib.bottom = function() {
	this.initialize(img.bottom);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,153,138);


(lib.btn = function() {
	this.initialize(img.btn);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,107,53);


(lib.h1 = function() {
	this.initialize(img.h1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,29,111);


(lib.h2 = function() {
	this.initialize(img.h2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,67,53);


(lib.h3 = function() {
	this.initialize(img.h3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,37,48);


(lib.h4 = function() {
	this.initialize(img.h4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,48,48);


(lib.h5 = function() {
	this.initialize(img.h5);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,55,93);


(lib.h6 = function() {
	this.initialize(img.h6);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,141,95);


(lib.head = function() {
	this.initialize(img.head);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,158,165);


(lib.logo_b = function() {
	this.initialize(img.logo_b);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,228,133);


(lib.logo_w = function() {
	this.initialize(img.logo_w);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,208,119);


(lib.pat = function() {
	this.initialize(img.pat);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,148,148);


(lib.top = function() {
	this.initialize(img.top);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,74,106);


(lib.Symbol50 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.btn();
	this.instance.setTransform(-53,-26);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-53,-26,107,53);


(lib.Symbol49 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#AD410F").s().p("AgKBMIgDgBIgBgDIAAgZQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAIADgBIAWAAQADAAAAAEIAAAZIgBADIgCABgAgHAfIgDgBIgBgDIgEhiIABgDIADgBIAXAAIADABIABADIgEBiIgBADIgDABg");
	this.shape.setTransform(67,0.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#AD410F").s().p("AgUA3QgJgEgHgHQgGgGgEgKQgCgJAAgNIAAgMQAAgMACgKQAEgJAGgGQAHgIAJgDQAKgDAKgBQAMABAJADQAJADAHAIQAGAGADAJQADAKABAMIAAAMQgBANgDAJQgDAKgGAGQgHAHgJAEQgJADgMAAQgKAAgKgDgAgMgYQgFAGAAAMIAAAMQAAANAFAFQAFAHAHAAQASAAgBgZIAAgMQABgYgSAAQgHAAgFAGg");
	this.shape_1.setTransform(58.5,2.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#AD410F").s().p("AgaA6QAAAAgBgBQAAAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhoIABgDIADgBIAYAAIACABIAAADIAAAEQAFgFAIgCQAGgCAIgBIADABQAAABAAAAQAAAAABABQAAAAAAABQAAAAAAAAIAAATIgBADIgCABIgCAAQgHAAgGACIgMAFIAABMIgBADIgCACg");
	this.shape_2.setTransform(49,2.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#AD410F").s().p("AgeA2QgHgEgEgGQgEgGgBgIQgCgJAAgJIAAhBIACgCIACgBIAZAAIADABIABACIAABBIAAAJQABADACADQABACADABIAIABQACAAAFgCIAJgEIAAhOIABgCIADgBIAZAAIACABIACACIAABpIgBADIgDABIgXAAIgCgBIgCgDIAAgFQgIAGgHACQgGADgJAAQgLAAgHgEg");
	this.shape_3.setTransform(38.5,2.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#AD410F").s().p("AgRA4QgJgDgHgGQgGgGgFgKQgFgKAAgOIAAgMQAAgMAEgKQAEgKAGgGQAHgIAJgDQAJgDAKgBQAMAAAJAEQAKAFAGAHQAGAGADAKQADAJABAMIAAAJQgBAFgEABIg+AAIABAIQACAEACADQACADAEACQAEABAEAAIAKAAIALAAIAKAAIAIgBIAAAAQAEAAAAADIAAAPIgBADQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAABIgTADQgKACgMgBQgIAAgJgCgAgLgaQgGAGAAAKIAAABIAjAAIAAgBQAAgKgFgHQgEgEgJAAQgHAAgEAFg");
	this.shape_4.setTransform(26.6,2.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#AD410F").s().p("AgQA4QgKgDgGgGQgIgGgEgKQgEgKgBgOIAAgMQABgMADgKQAEgKAGgGQAHgIAIgDQAKgDAKgBQAMAAAJAEQAKAFAGAHQAHAGADAKQACAJAAAMIAAAJQAAAFgDABIg+AAIABAIQAAAEADADQADADAEACQADABAEAAIAKAAIALAAIAKAAIAHgBIABAAQAEAAAAADIAAAPIgBADQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAgBABIgSADQgJACgNgBQgIAAgIgCgAgMgaQgEAGAAAKIAAABIAiAAIAAgBQAAgKgFgHQgFgEgIAAQgGAAgGAFg");
	this.shape_5.setTransform(9.6,2.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#AD410F").s().p("AgjBAQgNgOAAgYIAAgQQAAgVANgOQALgOAYAAIAIAAIAJABIAAgiIABgDIACgBIAZAAQAAAAAAAAQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAAAAAABIAACKIgBAEIgFACIgUAEQgMABgLAAQgWAAgNgNgAgGgKQgEABgCAEIgDAFIAAAKIAAAQIAAAKIADAIQACADAEACQADABADAAIAKAAIAHgBIAAg8IgIgBIgJAAQgDAAgDACg");
	this.shape_6.setTransform(-2.4,0.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#AD410F").s().p("AgWBIQgJgEgIgIQgGgIgEgNQgDgNAAgSIAAgPQAAgSADgNQAEgNAGgIQAIgIAJgEQALgEALAAQAMAAAKAEQAKAEAHAIQAHAIADANQAFANAAASIAAAPQAAASgFANQgDANgHAIQgHAIgKAEQgKAEgMAAQgLAAgLgEgAgHgtQgDACgDAFQgCAEgBAIQgCAHAAAMIAAAPQAAAMACAHQABAIACAEQADAFADACIAHABQADAAAEgBQAEgCACgFQADgEACgIQABgHAAgMIAAgPQAAgMgBgHQgCgIgDgEQgCgFgEgCQgEgBgDAAIgHABg");
	this.shape_7.setTransform(-19.9,0.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#AD410F").s().p("AgWBIQgJgEgIgIQgGgIgEgNQgDgNAAgSIAAgPQAAgSADgNQAEgNAGgIQAIgIAJgEQALgEALAAQAMAAAKAEQAKAEAHAIQAHAIADANQAEANABASIAAAPQgBASgEANQgDANgHAIQgHAIgKAEQgKAEgMAAQgLAAgLgEgAgGgtQgEACgDAFQgCAEgBAIQgCAHAAAMIAAAPQAAAMACAHQABAIACAEQADAFAEACIAGABQAEAAADgBQAEgCACgFQADgEACgIQABgHAAgMIAAgPQAAgMgBgHQgCgIgDgEQgCgFgEgCQgDgBgEAAIgGABg");
	this.shape_8.setTransform(-32.8,0.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#AD410F").s().p("AgVBIQgLgEgGgIQgHgIgDgNQgFgNAAgSIAAgPQAAgSAFgNQADgNAHgIQAGgIALgEQAJgEAMAAQAMAAAKAEQAKAEAHAIQAHAIAEANQADANAAASIAAAPQAAASgDANQgEANgHAIQgHAIgKAEQgKAEgMAAQgMAAgJgEgAgHgtQgDACgCAFQgDAEgCAIQgBAHAAAMIAAAPQAAAMABAHQACAIADAEQACAFADACIAHABQAEAAADgBQAEgCADgFQACgEABgIQACgHAAgMIAAgPQAAgMgCgHQgBgIgCgEQgDgFgEgCQgDgBgEAAIgHABg");
	this.shape_9.setTransform(-45.7,0.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#AD410F").s().p("AgKAQIgDgBIgCgDIAAgXQAAAAABgBQAAAAAAgBQAAAAAAAAQABgBAAAAIADgBIAVAAIADABQAAAAABABQAAAAAAAAQAAABAAAAQABABAAAAIAAAXIgCADIgDABg");
	this.shape_10.setTransform(-54.9,6.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#AD410F").s().p("AgYBKQgMgCgHgCIgDgBIgBgDIAAgQIABgDIADAAIAAAAIAVABIASAAQAKAAAEgEQAFgEgBgJIAAgDIgBgHQAAgDgCgCQgCgDgDgBIgGgBIgjAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAAAIAAgPQAAgEAEAAIAjAAQACAAADgCQAEgBACgDQACgCAAgDIABgHIAAgCQAAgHgEgEQgEgEgKAAIgKAAIgJAAIgKABIgKABQgBAAAAAAQAAAAgBAAQAAAAAAgBQgBAAAAAAIgBgDIAAgQQAAAAAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIACgBIATgFQAKgCAMAAQAKAAAKADQAJACAIAFQAGAFAEAHQADAIAAALIAAADQAAAJgEAJQgGAIgIAFQAJACAFAIQAEAIAAAKIAAADQAAAMgDAIQgFAIgGAGQgHAFgKADQgJADgKAAQgMAAgKgCg");
	this.shape_11.setTransform(-64.1,0.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-72.5,-14.2,145.1,28.6);


(lib.Symbol48 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#AD410F").s().p("AgSBNQgGgCgFgEQgEgEgDgGQgDgGAAgJIAAgDQAAgIADgGQACgGAGgEQAGgEAJgCQAJgCALAAIAPAAIAAgIQAAgLgEgFQgFgFgMAAIgPABIgOABIgBAAIgCgBQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIAAgHQAAgDAEgBIANgCIAQgBQAVAAAJAKQAJAKAAAQIAABGIgBADIgDABIgJAAIgDgBIgBgDIAAgFQgIAFgHACQgIADgGAAQgHAAgFgBgAgFAZQgHABgDACQgDACgCAEQgBAEAAAFIAAADQAAAKAFAEQAEAEAJAAQAFAAAHgCQAGgCAHgEIAAggIgPAAIgMABgAgIgvQgFgCgFgEQgEgDgDgFQgDgGgBgHIAAAAQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAIAAQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABQAAAEACADQACADADACIAGADIAFABIAHgBIAGgDQADgCABgDQACgDABgEQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIAHAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAABIAAAAQAAAHgDAGQgDAFgFADQgEAEgGACQgFACgGAAQgEAAgGgCg");
	this.shape.setTransform(76.7,-0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#AD410F").s().p("AgiBCQgLgJAAgOIAAgCQAAgIADgHQAEgHAFgDIgBgBQgFgDgCgEQgCgEAAgEIAAAAQAAgDACgEQACgEAEgCQgFgEgCgHQgCgFAAgHIAAgCQAAgHACgGQACgHAFgFQAFgEAIgEQAJgCANAAIAqAAQAAAAABAAQAAAAAAAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAIAAAFIgBADIgCABIgHABQACADACAFQACAFAAAIIAAACQAAAQgKAJQgLAJgVAAIgNgBIgKgEQgFADAAAEQAAAAAAAAQAAAAAAABQAAAAABABQAAAAAAAAIAFADIAcAIIAOADIAMAGQAGADADAFQADAFAAAHIAAACQAAAOgKAIQgLAJgXgBQgXABgLgJgAgZAcQgDAFAAAIIAAACQAAAEABAEIAFAFQADADAGABQAFABAIAAIANgBIAIgEQADgCABgDQACgDAAgEIAAgCQAAgGgGgDQgGgDgNgEIgUgGIgHAIgAgOg5QgFABgDADQgDADgBAEIgBAIIAAACIABAHQABADADADQADADAFACQAFACAJAAQAGAAAFgCQAGgBADgCQADgDABgEIABgIIAAgCIgBgIQgBgFgDgCQgDgDgGgBQgFgDgGAAQgIAAgGADg");
	this.shape_1.setTransform(66.3,4.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#AD410F").s().p("AgDBLIgDgBIgBgDIAAhkIABgDIADgBIAHAAIADABIABADIAABkIgBADIgDABgAgEgyQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAAAIAAgQIACgDIACgBIAJAAIACABIACADIAAAQQAAAAAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape_2.setTransform(58,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#AD410F").s().p("AAFBDQgFgCgCgDQgEgDgBgFQgCgFAAgIIAAhEIgTgCQgEgBAAgDIAAgFQAAgEAEAAIATAAIAAgTQAAgEAEAAIAIgCIABAAIACABIABADIAAAVIAWAAIACABIABADIAAAHQAAABAAAAQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgWAAIAABEQAAAIACACQACACAGAAIAMAAQAEAAAAADIAAAHQAAABAAABQAAAAgBABQAAAAgBAAQgBABAAAAIgHAAIgHABIgLgBg");
	this.shape_3.setTransform(51.7,1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#AD410F").s().p("AgOBLIgBAAIgBgCIABgBIAGgXQAAgDADAAIAMAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAABIgIAWIgCADIgEABgAgGAlIgIAAIgJgBIgIgCQgEgBAAgDIAAgHIABgCIACgBIABAAIAIABIAJABIAIAAIAGAAQAIAAAGgDQAEgDAAgIQAAgEgCgEQgEgBgJgFIgSgMQgJgGgFgHQgGgGAAgKQAAgIADgFQADgFAEgDQAFgDAGgCIAOgBIAQABIAOACQAEABAAADIAAAHQAAAAAAABQAAABgBAAQAAAAgBABQgBAAgBAAIAAAAIgNgBIgRgBQgHAAgGACQgEACAAAIQAAAFADADQAEADAGAEIASAMQAMAHAGAHQAEAGAAAIQAAAIgCAFQgDAGgFADQgFAEgHABQgHACgHAAIgGAAg");
	this.shape_4.setTransform(43.2,4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#AD410F").s().p("AgSBNQgGgCgFgEQgEgEgDgGQgDgGAAgJIAAgDQAAgIADgGQACgGAGgEQAGgEAJgCQAJgCALAAIAPAAIAAgIQAAgLgEgFQgFgFgMAAIgPABIgOABIgBAAIgCgBIgBgCIAAgHQAAgDAEgBIANgCIAQgBQAVAAAJAKQAJAKAAAQIAABGIgBADIgDABIgJAAIgDgBIgBgDIAAgFQgIAFgHACQgIADgGAAQgHAAgFgBgAgFAZQgHABgDACQgDACgCAEQgBAEAAAFIAAADQAAAKAFAEQAEAEAJAAQAFAAAHgCQAGgCAHgEIAAggIgPAAIgMABgAgIgvQgFgCgFgEQgEgDgDgFQgDgGgBgHIAAAAQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAIAAQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABQAAAEACADQACADADACIAGADIAFABIAHgBIAGgDQADgCABgDQACgDABgEQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIAHAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAABIAAAAQAAAHgDAGQgDAFgFADQgEAEgGACQgFACgGAAQgEAAgGgCg");
	this.shape_5.setTransform(33.1,-0.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#AD410F").s().p("AgKA1QgIgEgFgGQgGgHgCgJQgDgJAAgLIAAgNQAAgMADgIQACgJAGgHQAFgGAIgEQAIgDAIAAIAOABIALACIAEAAIAAADIAAAIIgBACIgCABIgBAAIgMgBIgNgBQgKABgGAHQgHAJAAARIAAANQAAARAHAJQAGAHAKAAIANAAIAMgBIABAAIACABIABACIAAAHIAAAEIgEABIgLABIgOABQgIAAgIgDg");
	this.shape_6.setTransform(23.7,2.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#AD410F").s().p("AgDBLIgDgBIgBgDIAAhkIABgDIADgBIAHAAIADABIABADIAABkIgBADIgDABgAgEgyQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAAAIAAgQIACgDIACgBIAJAAIACABIACADIAAAQQAAAAAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape_7.setTransform(11.7,0.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#AD410F").s().p("AgNBLIgCAAIAAgCIAAgBIAFgXQABgDAEAAIALAAQABAAAAAAQABAAAAAAQAAAAAAABQABAAAAABIgBABIgJAWIgCADIgCABgAgGAlIgIAAIgJgBIgIgCQgEgBAAgDIAAgHIABgCIADgBIABAAIAIABIAIABIAIAAIAGAAQAJAAAEgDQAFgDABgIQAAgEgEgEQgDgBgJgFIgRgMQgKgGgGgHQgFgGAAgKQAAgIADgFQADgFAFgDQAEgDAHgCIANgBIAPABIAQACQADABAAADIAAAHQAAAAAAABQAAABgBAAQAAAAgBABQgBAAAAAAIgBAAIgOgBIgQgBQgIAAgFACQgEACgBAIQAAAFAEADQAEADAGAEIASAMQANAHAEAHQAFAGAAAIQAAAIgDAFQgCAGgFADQgFAEgHABQgHACgHAAIgGAAg");
	this.shape_8.setTransform(4.6,4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#AD410F").s().p("AgSBNQgGgCgFgEQgEgEgDgGQgDgGAAgJIAAgDQAAgIADgGQACgGAGgEQAGgEAJgCQAJgCALAAIAPAAIAAgIQAAgLgEgFQgFgFgMAAIgPABIgOABIgBAAIgCgBIgBgCIAAgHQAAgDAEgBIANgCIAQgBQAVAAAJAKQAJAKAAAQIAABGIgBADIgDABIgJAAIgDgBIgBgDIAAgFQgIAFgHACQgIADgGAAQgHAAgFgBgAgFAZQgHABgDACQgDACgCAEQgBAEAAAFIAAADQAAAKAFAEQAEAEAJAAQAFAAAHgCQAGgCAHgEIAAggIgPAAIgMABgAgIgvQgFgCgFgEQgEgDgDgFQgDgGgBgHIAAAAQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAIAAQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABQAAAEACADQACADADACIAGADIAFABIAHgBIAGgDQADgCABgDQACgDABgEQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAHAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAABIAAAAQAAAHgDAGQgDAFgFADQgEAEgGACQgFACgGAAQgEAAgGgCg");
	this.shape_9.setTransform(-10.5,-0.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#AD410F").s().p("AgSBLQgJgBgJgCIgEgCIgBgCIAAiLIABgCIADgBIAKAAIADABIABACIAAAlIAMgBIALgBQAUABALANQALAMAAAWIAAAOQAAALgDAJQgCAJgGAHQgFAHgIADQgJAEgJAAIgSgBgAgXgTIAABOIAMABIALAAQANAAAGgJQAFgIAAgRIAAgOQAAgPgFgIQgGgJgNAAIgFAAIgGABIgHAAIgFAAg");
	this.shape_10.setTransform(-20.7,0.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#AD410F").s().p("AgSA3QgGgCgFgEQgEgEgDgGQgDgGAAgJIAAgDQAAgIADgGQACgGAGgCQAGgEAJgCQAJgCALAAIAPAAIAAgIQAAgNgEgFQgFgFgMAAIgPAAIgOABIgBAAIgCAAIgBgDIAAgHQAAgDAEAAIANgCIAQgBQAVAAAJAKQAJAKAAASIAABEIgBADIgDABIgJAAIgDgBIgBgDIAAgFQgIAEgHADQgIADgGAAQgHAAgFgBgAgFACQgHABgDADQgDACgCAEQgBADAAAGIAAADQAAAKAFAEQAEAEAJAAQAFgBAHgCQAGgCAHgDIAAghIgPAAIgMABg");
	this.shape_11.setTransform(-31.7,2.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#AD410F").s().p("AgOA2QgIgCgHgGQgGgGgEgJQgEgJAAgOIAAgQQAAgVAMgOQALgMAUAAQALAAAIADQAIADAFAHQAGAGADAJQADAJAAAKIAAAJQAAAEgEAAIhBAAIAAADQAAASAHAHQAHAIAMgBIASAAIARgCIABAAIACABIABACIAAAHIAAADIgEACIgRACIgSABQgHAAgIgCgAgSggQgHAHAAARIAAACIAzAAIAAgCQAAgRgHgIQgGgGgNgBQgLAAgHAIg");
	this.shape_12.setTransform(-42.1,2.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#AD410F").s().p("AgTA3IgDgBIgBgDIAAhkIABgDIADgBIAJAAIADABIABADIAAAEQAGgFAGgCQAHgCAHAAQAEAAAAADIAAAJQAAADgEAAIgOACIgMAGIAABSIgBADIgDABg");
	this.shape_13.setTransform(-50.6,2.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#AD410F").s().p("AAEBDQgEgCgCgDQgEgDgBgFQgCgFAAgIIAAhEIgTgCQgEgBAAgDIAAgFQAAgEAEAAIATAAIAAgTQAAgEAEAAIAIgCIABAAIACABIABADIAAAVIAVAAIADABIABADIAAAHQAAABAAAAQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgVAAIAABEQAAAIACACQADACAGAAIALAAQABAAABAAQABABAAAAQABAAAAABQAAABAAAAIAAAHQAAABAAABQAAAAgBABQAAAAgBAAQgBABgBAAIgGAAIgGABIgNgBg");
	this.shape_14.setTransform(-58.2,1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#AD410F").s().p("AgSA3QgGgCgFgEQgEgEgDgGQgDgGAAgJIAAgDQAAgIADgGQACgGAGgCQAGgEAJgCQAJgCALAAIAPAAIAAgIQAAgNgEgFQgFgFgMAAIgPAAIgOABIgBAAIgCAAIgBgDIAAgHQAAgDAEAAIANgCIAQgBQAVAAAJAKQAJAKAAASIAABEIgBADIgDABIgJAAIgDgBIgBgDIAAgFQgIAEgHADQgIADgGAAQgHAAgFgBgAgFACQgHABgDADQgDACgCAEQgBADAAAGIAAADQAAAKAFAEQAEAEAJAAQAFgBAHgCQAGgCAHgDIAAghIgPAAIgMABg");
	this.shape_15.setTransform(-72.5,2.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#AD410F").s().p("AgEBLIgCgBIgBgDIAAiNIABgDIACgBIAJAAIACABIABADIAACNIgBADIgCABg");
	this.shape_16.setTransform(-79.9,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-84.3,-13.9,168.6,27.9);


(lib.Symbol47 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#AD410F").s().p("AgSA3QgGgCgFgEQgEgEgDgGQgDgGAAgJIAAgDQAAgIADgGQACgGAGgCQAGgEAJgCQAJgCALAAIAPAAIAAgIQAAgNgEgFQgFgFgMAAIgPAAIgOABIgBAAIgCAAIgBgDIAAgHQAAgDAEAAIANgCIAQgBQAVAAAJAKQAJAKAAASIAABEIgBADIgDABIgJAAIgDgBIgBgDIAAgFQgIAEgHADQgIADgGAAQgHAAgFgBgAgFACQgHABgDADQgDACgCAEQgBADAAAGIAAADQAAAKAFAEQAEAEAJAAQAFgBAHgCQAGgCAHgDIAAghIgPAAIgMABg");
	this.shape.setTransform(85.3,2.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#AD410F").s().p("AgOA2QgIgCgHgGQgGgGgEgJQgEgJAAgOIAAgQQAAgVAMgOQALgMAUAAQALAAAIADQAIADAFAHQAGAGADAJQADAJAAAKIAAAJQAAAEgEAAIhBAAIAAADQAAASAHAHQAHAIAMgBIASAAIARgCIABAAIACABIABACIAAAHIAAADIgEACIgRACIgSABQgHAAgIgCgAgSggQgHAHAAARIAAACIAzAAIAAgCQAAgRgHgIQgGgGgNgBQgLAAgHAIg");
	this.shape_1.setTransform(74.9,2.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#AD410F").s().p("AAEBDQgEgCgCgDQgDgDgCgFQgCgFAAgIIAAhEIgTgCQgEgBAAgDIAAgFQAAgEAEAAIATAAIAAgTQAAgEAEAAIAIgCIABAAIACABIABADIAAAVIAVAAIADABIACADIAAAHQAAABgBAAQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgVAAIAABEQAAAIACACQADACAGAAIALAAQABAAABAAQABABAAAAQAAAAABABQAAABAAAAIAAAHQAAABAAABQAAAAgBABQAAAAgBAAQgBABgBAAIgGAAIgGABIgNgBg");
	this.shape_2.setTransform(65.6,1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#AD410F").s().p("AgSA3QgGgCgFgEQgEgEgDgGQgDgGAAgJIAAgDQAAgIADgGQACgGAGgCQAGgEAJgCQAJgCALAAIAPAAIAAgIQAAgNgEgFQgFgFgMAAIgPAAIgOABIgBAAIgCAAIgBgDIAAgHQAAgDAEAAIANgCIAQgBQAVAAAJAKQAJAKAAASIAABEIgBADIgDABIgJAAIgDgBIgBgDIAAgFQgIAEgHADQgIADgGAAQgHAAgFgBgAgFACQgHABgDADQgDACgCAEQgBADAAAGIAAADQAAAKAFAEQAEAEAJAAQAFgBAHgCQAGgCAHgDIAAghIgPAAIgMABg");
	this.shape_3.setTransform(56.3,2.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#AD410F").s().p("AAEBDQgEgCgCgDQgEgDgBgFQgCgFAAgIIAAhEIgTgCQgEgBAAgDIAAgFQAAgEAEAAIATAAIAAgTQAAgEAEAAIAIgCIABAAIACABIABADIAAAVIAVAAIADABIABADIAAAHQAAABAAAAQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgVAAIAABEQAAAIACACQADACAGAAIALAAQABAAABAAQABABAAAAQABAAAAABQAAABAAAAIAAAHQAAABAAABQAAAAgBABQAAAAgBAAQgBABgBAAIgGAAIgGABIgNgBg");
	this.shape_4.setTransform(47.5,1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#AD410F").s().p("AgDBLIgDgBIgBgDIAAhkIABgDIADgBIAHAAIADABIABADIAABkIgBADIgDABgAgEgyQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAAAIAAgQIACgDIACgBIAJAAIACABIACADIAAAQQAAAAAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape_5.setTransform(41.2,0.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#AD410F").s().p("AgKA1QgEgCgCgHIgbhdIAAgCQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAAAAAIALAAQADAAACAEIAWBVIACAEIABABIACgBIABgEIAYhVQABgEACAAIALAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAACIgbBdQgCAHgFACQgFACgGAAQgFAAgFgCg");
	this.shape_6.setTransform(33.5,2.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#AD410F").s().p("AgDBLIgDgBIgBgDIAAhkIABgDIADgBIAHAAIADABIABADIAABkIgBADIgDABgAgEgyQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAAAIAAgQIACgDIACgBIAJAAIACABIACADIAAAQQAAAAAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape_7.setTransform(25.7,0.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#AD410F").s().p("AAFBDQgFgCgCgDQgDgDgCgFQgCgFAAgIIAAhEIgTgCQgEgBAAgDIAAgFQAAgEAEAAIATAAIAAgTQAAgEAEAAIAIgCIABAAIACABIABADIAAAVIAVAAIADABIACADIAAAHQAAABgBAAQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgVAAIAABEQAAAIACACQADACAFAAIAMAAQABAAABAAQAAABABAAQAAAAABABQAAABAAAAIAAAHQAAABAAABQAAAAgBABQAAAAgBAAQgBABgBAAIgGAAIgGABIgMgBg");
	this.shape_8.setTransform(19.4,1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#AD410F").s().p("AgSA3QgGgCgFgEQgEgEgDgGQgDgGAAgJIAAgDQAAgIADgGQACgGAGgCQAGgEAJgCQAJgCALAAIAPAAIAAgIQAAgNgEgFQgFgFgMAAIgPAAIgOABIgBAAIgCAAQAAAAgBAAQAAgBAAAAQAAAAAAgBQAAAAAAgBIAAgHQAAgDAEAAIANgCIAQgBQAVAAAJAKQAJAKAAASIAABEIgBADIgDABIgJAAIgDgBIgBgDIAAgFQgIAEgHADQgIADgGAAQgHAAgFgBgAgFACQgHABgDADQgDACgCAEQgBADAAAGIAAADQAAAKAFAEQAEAEAJAAQAFgBAHgCQAGgCAHgDIAAghIgPAAIgMABg");
	this.shape_9.setTransform(10.1,2.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#AD410F").s().p("AgOA2QgIgCgHgGQgGgGgEgJQgEgJAAgOIAAgQQAAgVAMgOQALgMAUAAQALAAAIADQAIADAFAHQAGAGADAJQADAJAAAKIAAAJQAAAEgEAAIhBAAIAAADQAAASAHAHQAHAIAMgBIASAAIARgCIABAAIACABIABACIAAAHIAAADIgEACIgRACIgSABQgHAAgIgCgAgSggQgHAHAAARIAAACIAzAAIAAgCQAAgRgHgIQgGgGgNgBQgLAAgHAIg");
	this.shape_10.setTransform(-0.4,2.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#AD410F").s().p("AgTA3IgDgBIgBgDIAAhkIABgDIADgBIAJAAIADABIABADIAAAEQAGgFAGgCQAHgCAHAAQAEAAAAADIAAAJQAAADgEAAIgOACIgMAGIAABSIgBADIgDABg");
	this.shape_11.setTransform(-8.8,2.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#AD410F").s().p("AgKA1QgIgEgFgGQgGgHgCgJQgDgJAAgLIAAgNQAAgMADgIQACgJAGgHQAFgGAIgEQAIgDAIAAIAOABIALACIAEAAIAAADIAAAIIgBACIgCABIgBAAIgMgBIgNgBQgKABgGAHQgHAJAAARIAAANQAAARAHAJQAGAHAKAAIANAAIAMgBIABAAIACABIABACIAAAHIAAAEIgEABIgLABIgOABQgIAAgIgDg");
	this.shape_12.setTransform(-17.1,2.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#AD410F").s().p("AgDBLIgDgBIgBgDIAAhkIABgDIADgBIAHAAIADABIABADIAABkIgBADIgDABgAgEgyQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAAAIAAgQIACgDIACgBIAJAAIACABIACADIAAAQQAAAAAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape_13.setTransform(-29.1,0.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#AD410F").s().p("AgJBWIgCAAIAAgBIAAgCIAFgWQABgDAEgBIALAAQABAAAAABQABAAAAAAQAAAAAAABQABAAAAAAIgBACIgLAWIgBADIgBAAgAAFAwQgFgCgCgCQgDgEgCgEQgCgGAAgIIAAhEIgTgCQgEAAAAgDIAAgGQAAgEAEABIATAAIAAgUQAAgDAEgBIAIgCIABAAIACABIABADIAAAWIAVAAIAEABIABACIAAAHIgBADIgEABIgVAAIAABEQAAAIACACQADACAFABIAMAAQABAAABAAQAAAAABAAQAAABABAAQAAABAAABIAAAHQAAAAAAABQAAAAgBABQAAAAgBABQgBAAgBAAIgGAAIgHABIgLgBg");
	this.shape_14.setTransform(-35.4,2.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#AD410F").s().p("AgSAHQgEAAAAgEIAAgFIABgDIADgBIAlAAQAEAAAAAEIAAAFQAAAEgEAAg");
	this.shape_15.setTransform(-42.6,1.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#AD410F").s().p("AgOA2QgIgCgHgGQgGgGgEgJQgEgJAAgOIAAgQQAAgVAMgOQALgMAUAAQALAAAIADQAIADAFAHQAGAGADAJQADAJAAAKIAAAJQAAAEgEAAIhBAAIAAADQAAASAHAHQAHAIAMgBIASAAIARgCIABAAIACABIABACIAAAHIAAADIgEACIgRACIgSABQgHAAgIgCgAgSggQgHAHAAARIAAACIAzAAIAAgCQAAgRgHgIQgGgGgNgBQgLAAgHAIg");
	this.shape_16.setTransform(-51.4,2.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#AD410F").s().p("AAcA3IgDgBIgBgDIAAhAIgBgMQgCgFgCgDQgDgDgEgCIgKgBQgEAAgHACIgOAGIAABSIgBADIgDABIgKAAIgDgBIgBgDIAAhkIABgDIADgBIAKAAIADABIABADIAAAEQAIgFAIgCQAHgCAHAAQASAAAIALQAJAKAAAUIAABAIgCADIgCABg");
	this.shape_17.setTransform(-62.4,2.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#AD410F").s().p("AggAsQgJgKAAgUIAAhAIABgDIADgBIAKAAIADABIABADIAABAQAAAHABAFQACAFACADQADADAEACIAKABQAEAAAHgCIAOgGIAAhSIABgDIADgBIAKAAIACABIACADIAABkIgCADIgCABIgKAAIgDgBIgBgDIAAgEQgIAFgIACQgHACgHAAQgSAAgIgLg");
	this.shape_18.setTransform(-73.6,2.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#AD410F").s().p("AgqBLIgCgBIgBgDIAAiKQAAgFAEAAIAQgBIASgBQAKAAAKADQAKACAHAFQAIAFAFAJQADAIAAAMIAAACQAAANgDAJQgFAGgIAFQgHAFgKADQgKACgKAAIgLAAIgJgBIAAA5IgBADIgDABgAgbg6IAAA6IAEAAIAGAAIAFAAIAFAAQASAAAJgFQAIgHAAgQIAAgCQAAgPgJgGQgJgHgRAAIgLAAIgJAAg");
	this.shape_19.setTransform(-84.7,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-92.9,-13.9,185.9,27.9);


(lib.Symbol45 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgNBbQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAAAIAAgfQAAAAAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAIADgBIAaAAQAFAAAAAEIAAAfIgBADQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAgAgIAlIgFgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIgEh2QAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAIADgBIAcAAIAEABQAAAAABAAQAAABAAAAQAAABAAAAQAAABAAAAIgFB2QAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAAAAAg");
	this.shape.setTransform(33.1,0.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgMATQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQgBAAAAgBIAAgcQAAAAABgBQAAAAAAgBQAAAAAAAAQABgBAAAAIAEgBIAZAAIAEABQAAAAABABQAAAAAAAAQAAABAAAAQABABAAAAIAAAcQAAABgBAAQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAg");
	this.shape_1.setTransform(26.5,7.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgaBWQgMgEgJgKQgHgKgFgPQgEgPAAgWIAAgTQAAgVAEgQQAFgPAHgKQAJgKAMgEQAMgFAOAAQAOAAANAFQAMAEAIAKQAIAKAEAPQAFAQAAAVIAAATQAAAWgFAPQgEAPgIAKQgIAKgMAEQgNAFgOAAQgOAAgMgFgAgIg2QgEACgDAGQgDAFgDAJQgBAJAAAOIAAATQAAAOABAJQADAJADAGQADAFAEACQAEACAEAAQAFAAAEgCQAEgCADgFQADgGACgJQACgJAAgOIAAgTQAAgOgCgJQgCgJgDgFQgDgGgEgCQgEgCgFAAQgEAAgEACg");
	this.shape_2.setTransform(15.5,0.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgNATQAAAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIAAgcQAAAAAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAIADgBIAaAAIAEABQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAAAIAAAcQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAg");
	this.shape_3.setTransform(4.4,7.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgaBWQgMgEgIgKQgJgKgEgPQgEgPAAgWIAAgTQAAgVAEgQQAEgPAJgKQAIgKAMgEQAMgFAOAAQAOAAAMAFQAMAEAJAKQAIAKAFAPQAEAQAAAVIAAATQAAAWgEAPQgFAPgIAKQgJAKgMAEQgMAFgOAAQgOAAgMgFgAgIg2QgFACgDAGQgCAFgCAJQgCAJAAAOIAAATQAAAOACAJQACAJACAGQADAFAFACQAEACAEAAQAFAAADgCQAFgCADgFQADgGADgJQABgJAAgOIAAgTQAAgOgBgJQgDgJgDgFQgDgGgFgCQgDgCgFAAQgEAAgEACg");
	this.shape_4.setTransform(-6.6,0.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgMATQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQgBAAAAgBIAAgcQAAAAABgBQAAAAAAgBQAAAAAAAAQABgBAAAAIAEgBIAaAAIADABQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAAAIAAAcQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAAAAAg");
	this.shape_5.setTransform(-17.7,7.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgzBZQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAAAAAgBIgBgDIAAgZIABgDIADgBIAgAAIAAhmIgfAOIgDABQgBAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBIAAgbQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABAAIArgVIAFgBIAUAAQAFAAgBAFIAACKIAhAAIADABQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAAAIAAAZQAAAAAAABQAAAAAAABQAAAAAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAAAAAg");
	this.shape_6.setTransform(-28.3,0.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-38.5,-16.7,77.1,33.5);


(lib.Symbol44 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgcBEQgHgCgGgFQgGgEgDgIQgEgIAAgMIAAgCQAAgVAOgIQAOgKAdAAIANAAIAAgIQAAgLgEgDQgGgDgGAAIgLAAIgMABIgJAAIgIABIgBAAIgDgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBAAAAgBIAAgTQABgEAEgBIATgEQALgBALAAQAMAAAKADQALACAHAGQAHAGAEAJQAEAKAAANIAABTQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAIgbAAIgDgBQAAgBgBAAQAAAAAAgBQAAAAAAgBQgBAAAAgBIAAgDQgGAFgIACQgGADgLAAQgIAAgHgCgAgFAKIgGAEQgDACgBADIgBAIIAAACQAAAIAEACQAEACAHAAQAEAAAEgBIAKgEIAAgbIgOAAIgIABg");
	this.shape.setTransform(49.8,2.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUBDQgLgDgJgHQgIgHgFgMQgGgMAAgRIAAgPQAAgOAFgMQAEgMAHgIQAIgIALgFQAMgEAMAAQAPAAALAFQALAEAIAJQAHAIADAMQAEALAAAOIAAAMQAAAGgEAAIhMAAIAAAAQAAAFACAFQABAFADADQADAEAFACQAFACAEAAIAMAAIAOAAIALgBIAJgBIABAAQAFAAAAAEIAAASIgBAFIgFACIgWAEQgLABgPAAQgJAAgLgDgAgPgfQgFAGgBAOIAAABIAqAAIAAgBQAAgOgFgGQgGgHgKAAQgIAAgHAHg");
	this.shape_1.setTransform(36.3,2.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAYBFQAAAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQgBAAAAgBIAAhOIAAgKQgBgFgCgCQgCgDgDgBIgJgBQgDAAgGACIgMAGIAABcQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAIgdAAQAAAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIAAh+IABgDIADgBIAbAAQABAAAAAAQAAAAABAAQAAAAABABQAAAAABAAIABADIAAAGQAJgHAKgCQAGgDAMAAQANAAAIAEQAJAEAEAIQAFAHACAKQABAKABALIAABOQAAABgBAAQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAg");
	this.shape_2.setTransform(21.8,2.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgkBBQgIgEgGgIQgEgHgCgKQgCgKAAgLIAAhOQAAgBABAAQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAIAcAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABIAABOIAAAKQAAAFADACQACADADABQAEABAFAAQAEAAAFgCIALgGIAAhcQAAgBABAAQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAIAdAAQAAAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQAAAAAAABIAAB9QAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAAAAAIgbAAQgBAAAAAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAgFQgKAHgJACQgHADgLAAQgNAAgIgEg");
	this.shape_3.setTransform(7.1,2.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNBcIgDgCQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAAAAAgBIAAh+IACgDIADgCIAbAAQABAAAAABQABAAAAAAQABAAAAAAQAAABABAAIABADIAAB+QAAABAAAAQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAgAgOg7IgDgCQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAAAAAgBIAAgWQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAABgBIADgBIAdAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABAAIABAEIAAAWIgBADQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_4.setTransform(-3.7,0.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgKBGIgMgBIgLgCIgKgCQgFgBAAgEIAAgUIABgDIAEgBIABAAIAKABIAMABIALABIAIAAQAGAAADgCQADgDAAgEQAAgDgCgCQgCgDgFgCIgdgSQgKgEgGgJQgGgJAAgMQAAgSAMgKQANgJAYAAQANAAAJABIATAEQAFABAAAFIAAATQAAAFgEAAIgBAAIgHgBIgLgBIgLgBIgLAAQgFAAgDABQgDACAAAEQAAAAAAABQABABAAAAQAAABAAAAQABABAAAAIAGAEIAcARQAHAEAFADIAHAJQADAFABAEIABAKQAAAIgDAIQgDAHgHAGQgGAFgKADQgJADgMAAIgKAAg");
	this.shape_5.setTransform(-13.2,2.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgfBFQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAh+IABgDIADgBIAdAAIADABIAAADIAAAFQAHgFAIgDQAJgDAIAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABQAAAAAAABIAAAWIgBAEIgCABIgCAAQgJAAgIACIgOAGIAABcQAAABAAAAQAAABgBAAQAAABAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_6.setTransform(-23.5,2.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgUBDQgLgDgIgHQgJgHgGgMQgEgMAAgRIAAgPQAAgOADgMQAEgMAIgIQAIgIALgFQAMgEAMAAQAPAAALAFQALAEAHAJQAIAIADAMQAFALAAAOIAAAMQAAAGgGAAIhKAAIAAAAQgBAFACAFQABAFADADQADAEAEACQAGACAFAAIAMAAIAMAAIANgBIAJgBIAAAAQAFAAAAAEIAAASIgBAFIgEACIgXAEQgLABgPAAQgKAAgKgDgAgPgfQgFAGAAAOIAAABIAqAAIAAgBQgBgOgGgGQgFgHgKAAQgIAAgHAHg");
	this.shape_7.setTransform(-35.8,2.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgKBEIgKgDQgEgDgEgFQgDgFgCgIIgfhrIAAgBQAAgEAEAAIAgAAQABAAAAAAQAAAAABAAQAAAAAAABQABAAAAAAIACAEIAUBcQACAFABAAQACAAABgFIAUhcIACgEQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAIAfAAIADABQAAAAABAAQAAABAAAAQAAAAAAABQABAAAAABIgBABIgeBrQgCAIgEAFQgEAFgEADQgFACgFABIgKABIgKgBg");
	this.shape_8.setTransform(-49.9,2.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58.9,-16.7,118,33.5);


(lib.Symbol43 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgcBEQgIgCgFgFQgGgEgDgIQgEgIAAgMIAAgCQAAgVAOgIQAOgKAdAAIANAAIAAgIQAAgLgFgDQgEgDgHAAIgMAAIgLABIgKAAIgHABIgBAAIgDgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIAAgTQgBgEAFgBIASgEQAMgBALAAQALAAALADQALACAHAGQAHAGAEAJQAEAKAAANIAABTQAAABAAAAQAAABAAAAQgBABAAAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAQAAAAgBAAIgbAAIgDgBQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIAAgDQgIAFgHACQgGADgLAAQgIAAgHgCgAgFAKIgHAEQgCACgBADIgBAIIAAACQAAAIAEACQADACAIAAQADAAAGgBIAJgEIAAgbIgOAAIgIABg");
	this.shape.setTransform(35.8,2.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgNBbQgBAAAAAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAAAIAAitIABgDQABAAAAgBQABAAAAAAQABAAAAAAQAAAAABAAIAbAAIADABIACADIAACtQAAAAAAAAQAAABAAAAQgBABAAAAQAAABgBAAIgDABg");
	this.shape_1.setTransform(26,0.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgUBDQgLgDgIgHQgJgHgGgMQgEgMAAgRIAAgPQAAgOADgMQAEgMAIgIQAIgIAMgFQAKgEANAAQAPAAALAFQALAEAHAJQAIAIAEAMQADALABAOIAAAMQAAAGgGAAIhKAAIAAAAQgBAFACAFQABAFADADQADAEAEACQAGACAFAAIAMAAIAMAAIANgBIAJgBIAAAAQAFAAAAAEIAAASIgBAFIgEACIgXAEQgLABgPAAQgJAAgLgDgAgOgfQgHAGABAOIAAABIAqAAIAAgBQAAgOgHgGQgFgHgKAAQgJAAgFAHg");
	this.shape_2.setTransform(9.3,2.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgeA3QgPgQAAgdIAAgSQAAgeAPgQQAQgPAXAAIATABIANACIAEACIABAEIAAAVIgBADIgEABIAAAAIgNgBIgQAAIgIABQgEABAAAEQgDADgCAFQgBAGAAAIIAAASQAAAIABAFIAFAJQAAADAEABIAIABIAQAAIANgBIAAAAIAEABIABADIAAAVIgBAEQAAAAgBAAQAAABgBAAQAAAAgBAAQgBABAAAAIgNACIgTABQgXAAgQgPg");
	this.shape_3.setTransform(-3.5,2.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgUBDQgLgDgIgHQgJgHgGgMQgEgMAAgRIAAgPQAAgOADgMQAFgMAHgIQAIgIAMgFQAKgEANAAQAPAAALAFQALAEAHAJQAIAIAEAMQADALAAAOIAAAMQAAAGgEAAIhMAAIAAAAQABAFABAFQABAFADADQADAEAEACQAFACAGAAIALAAIAOAAIAMgBIAJgBIAAAAQAFAAAAAEIAAASIgBAFIgEACIgXAEQgLABgPAAQgJAAgLgDgAgOgfQgHAGAAAOIAAABIArAAIAAgBQAAgOgHgGQgFgHgKAAQgJAAgFAHg");
	this.shape_4.setTransform(-16.2,2.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgfBFQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAh+IABgDIADgBIAdAAIADABIAAADIAAAFQAHgFAIgDQAJgDAIAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABQAAAAAAABIAAAWIgBAEIgCABIgCAAQgJAAgIACIgOAGIAABcQAAABAAAAQAAABgBAAQAAABAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_5.setTransform(-27.6,2.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AACBTQgFgCgFgEQgFgFgCgIQgDgIAAgNIAAhDIgUgEIgDgCQAAAAgBAAQAAAAAAgBQAAAAAAgBQAAAAAAAAIAAgQQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBAAAAIAUAAIAAgUIABgCIADgCIAcgFIAAAAIAEABQAAAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIAAAZIATAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAIACADIAAATQAAABgBAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAABgBAAIgTAAIAABDQAAAIABABQACACAFABIALAAQAFAAABADIAAATQAAAEgFABIgKACIgJAAQgKAAgIgBg");
	this.shape_6.setTransform(-38,1.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-44.9,-16.7,90,33.5);


(lib.Symbol42 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgcBEQgIgCgFgFQgGgEgEgIQgDgIAAgMIAAgCQAAgVAOgIQAOgKAdAAIANAAIAAgIQAAgLgEgDQgGgDgGAAIgLAAIgMABIgKAAIgHABIgBAAIgDgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAgBgBIAAgTQABgEAEgBIATgEQALgBALAAQALAAALADQALACAHAGQAHAGAEAJQAEAKAAANIAABTQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAIgbAAIgDgBQAAgBgBAAQAAAAAAgBQAAAAAAgBQgBAAAAgBIAAgDQgGAFgIACQgGADgLAAQgIAAgHgCgAgFAKIgGAEQgDACgBADIgBAIIAAACQAAAIAEACQADACAIAAQAEAAAEgBIAKgEIAAgbIgOAAIgIABg");
	this.shape.setTransform(43,2.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgNBcIgDgCQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAAAAAgBIAAh+IACgDIADgCIAbAAQABAAAAABQABAAAAAAQABAAAAAAQAAABABAAIABADIAAB+QAAABAAAAQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAgAgOg7IgDgCQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAAAAAgBIAAgWQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAABgBIADgBIAdAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABAAIABAEIAAAWIgBADQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_1.setTransform(33,0.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAZBFQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQgBAAAAgBIAAhOIAAgKQgBgFgCgCQgCgDgDgBIgJgBQgEAAgFACIgLAGIAABcQAAABgBAAQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAIgdAAQAAAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIAAh+IABgDIADgBIAbAAQABAAAAAAQAAAAABAAQAAAAABABQAAAAAAAAIACADIAAAGQAKgHAJgCQAHgDALAAQANAAAIAEQAJAEAEAIQAFAHACAKQACAKAAALIAABOQAAABgBAAQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAg");
	this.shape_2.setTransform(22.2,2.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgcBcQgIgCgFgFQgGgEgDgJQgEgHAAgMIAAgCQAAgWAOgJQAOgKAdAAIANAAIAAgIQAAgJgEgDQgFgDgHAAIgMAAIgLABIgJAAIgIABIgBAAIgDgBQAAgBgBAAQAAAAAAgBQAAAAAAgBQgBAAAAgBIAAgTQAAgEAFgBIATgEQALgBALgBQALAAALADQAKADAIAGQAHAGAEAJQAEAJAAAMIAABVQAAABAAAAQAAAAAAABQgBAAAAABQAAAAAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQAAAAgBAAIgbAAIgDgCQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAAAAAgBIAAgDQgIAFgHACQgGADgLAAQgIAAgHgCgAgFAiIgHAEQgCABgBAEIgBAIIAAACQAAAHAEACQADADAIAAQADAAAGgCIAJgEIAAgaIgOAAIgIABgAAYg5QgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAIgCgCIgQgRIgNARIgDACIgDABIgZAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIABgDIAVgcIAEgCIADgBIAkAAIAEABIADACIAVAcIABADQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAg");
	this.shape_3.setTransform(7.8,0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA4BFQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhQQAAgLgDgEQgDgFgIAAIgJABIgKAEIABAPIAABQQAAABAAAAQAAABAAAAQgBABAAAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAQAAAAgBAAIgbAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhQQAAgLgDgEQgDgFgIAAQgEAAgEACIgKAFIAABdQAAABAAAAQAAABAAAAQgBABAAAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAIgdAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAh+IACgDIACgBIAcAAQABAAAAAAQAAAAABAAQAAAAABABQAAAAABAAIABADIAAAGQAHgFAJgEQAJgDALAAQAJAAAHADQAFACAFAHIAJgGIAJgDIAKgCIALgBQAMAAAHAEQAJAEAFAGQAEAHACAKQACAKAAALIAABQQAAABAAAAQAAABAAAAQgBABAAAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_4.setTransform(-9.2,2.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYBCQgLgFgIgIQgIgIgEgLQgEgMAAgOIAAgPQAAgOAEgMQAEgLAIgIQAIgIALgFQALgEANAAQAOAAALAEQALAFAIAIQAIAIAEALQAEAMAAAOIAAAPQAAAOgEAMQgEALgIAIQgIAIgLAFQgLAEgOAAQgNAAgLgEgAgPgdQgFAIAAAOIAAAPQAAAPAFAHQAGAHAJAAQAVAAAAgdIAAgPQAAgdgVAAQgJAAgGAHg");
	this.shape_5.setTransform(-26.8,2.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAcBaQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAgBgBIgCgDIgeg9IgDAAIgIAAIgJAAIAAA9QAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgfAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBAAAAgBIgBgDIAAifQAAgGACgDQADgCAFgBIAKgBIAMgBIAOAAIANgBQANAAAOADQANADAKAGQAJAHAGALQAFALAAAPIAAAEQAAATgJAKQgIALgOAGIAlBDIAAADQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAgAgbgHIAEAAIAFAAIAFAAIADAAIAOgBQAHgBADgDQAEgDACgEQACgEAAgGIAAgEQAAgLgJgFQgIgFgNAAIgEAAIgGAAIgFABIgEAAg");
	this.shape_6.setTransform(-41.6,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.1,-16.7,104.3,33.5);


(lib.Symbol39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.h6();
	this.instance.setTransform(-70,-47);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-70,-47,141,95);


(lib.Symbol38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.h5();
	this.instance.setTransform(-27,-46);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-27,-46,55,93);


(lib.Symbol37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.h4();
	this.instance.setTransform(-24,-24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-24,-24,48,48);


(lib.Symbol36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.h3();
	this.instance.setTransform(-18,-24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-18,-24,37,48);


(lib.Symbol35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.h2();
	this.instance.setTransform(-33,-26);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-33,-26,67,53);


(lib.Symbol34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.h1();
	this.instance.setTransform(-14,-55);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-14,-55,29,111);


(lib.Symbol33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.head();
	this.instance.setTransform(-79,-82);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-79,-82,158,165);


(lib.Symbol32 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F9D2A0").s().p("AiSTeMAAAgm7IAcAAIAAAcIAcAAIAAAcIAcAAIAAAcIAcAAIAAAcIAcAAIAAAcIAaAAIAAgcIAcAAIAAgcIAcAAIAAgcIAcAAIAAgcIArAAMAAAAmfgAgGyJIAAgcIgcAAIAAgcIAcAAIAAAcIAaAAIAAAcgAAUylIAAgcIgaAAIAAgcIAaAAIAAAcIAcAAIAAAcgAgGzBg");
	this.shape.setTransform(0.8,116.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-14,-8.4,29.5,249.3);


(lib.Symbol29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.bg();
	this.instance.setTransform(-168,-140);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,-140,336,280);


(lib.Symbol27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.top, null, new cjs.Matrix2D(1,0,0,1,-35,-49.4)).s().p("ACZFuIhnAAIkkg6IhChCIBBiFIAAhOIgthiIAnmWIEhgUIENAUIgiImIAACnIgXD6g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-31,-49.4,62,98.9);


(lib.Symbol26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.top, null, new cjs.Matrix2D(1,0,0,1,-6.2,-84.6)).s().p("Ag9BEIAAiHIBnAlIAUBig");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.2,-6.8,12.4,13.8);


(lib.Symbol25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.top, null, new cjs.Matrix2D(1,0,0,1,-5.2,-56.5)).s().p("AgjAmIAAgfIgQAAIAAgsIBnAAIAABLg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5.2,-3.9,10.5,7.8);


(lib.Symbol24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.top, null, new cjs.Matrix2D(1,0,0,1,-12.5,-101.8)).s().p("Ag8ApIAAhRIB5AAIAABRg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.2,-4.1,12.4,8.3);


(lib.Symbol23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.top, null, new cjs.Matrix2D(1,0,0,1,-45.1,-92.5)).s().p("AgyA/IAAh9IBlAAIAAB9g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5.1,-6.4,10.3,12.8);


(lib.Symbol22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.top, null, new cjs.Matrix2D(1,0,0,1,-68.3,-65.6)).s().p("Ag4BTIAAilIBxAAIAAClg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5.7,-8.3,11.5,16.8);


(lib.Symbol20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.bottom, null, new cjs.Matrix2D(1,0,0,1,-83.2,-87.7)).s().p("An4H2IAAjOIhnhrIAAjDIBzkCIAAjtICFB8IDJAAIAFBzICXhuIElAuICOiPIAADTICvCWIhxBaIAAC9IgfAZIAAEyg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.8,-50.2,121.6,100.5);


(lib.Symbol19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#8A962B").s().p("AgxAyIAAhjIBjAAIAABjg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5,-5,10,10);


(lib.Symbol18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.bottom, null, new cjs.Matrix2D(1,0,0,1,-12.4,-24.2)).s().p("Ah7BjIAAjFID3AAIAADFg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-12.4,-10,24.8,20);


(lib.Symbol17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.bottom, null, new cjs.Matrix2D(1,0,0,1,-77.4,-47.7)).s().p("AhQBWIAAirIChAAIhYCrg");
	this.shape.setTransform(-0.9,19.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-9,10.8,16.4,17.4);


(lib.Symbol16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.bottom, null, new cjs.Matrix2D(1,0,0,1,-57.2,-35.3)).s().p("AhjCRIAAkhIBjAAIAAAvIBkAAIAADyg");
	this.shape.setTransform(0,10.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-10,-4.2,20.1,29.2);


(lib.Symbol15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.bottom, null, new cjs.Matrix2D(1,0,0,1,-102,-40.4)).s().p("AhmCQIAAkfIDNAAIAAEfg");
	this.shape.setTransform(0,13);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-10.3,-1.5,20.8,29);


(lib.Symbol14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.bottom, null, new cjs.Matrix2D(1,0,0,1,-124.9,-14)).s().p("Ah2BhIAAjBIDtAAIAADBg");
	this.shape.setTransform(0,2.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-11.9,-7.5,23.9,19.4);


(lib.Symbol13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.bottom, null, new cjs.Matrix2D(1,0,0,1,-139.8,-51.2)).s().p("AiDBqIAAjTIEHAAIAADTg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-13.2,-10.6,26.4,21.2);


(lib.Symbol12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.bottom, null, new cjs.Matrix2D(1,0,0,1,-142.9,-95.3)).s().p("AhkBfIAAi9IDJAAIAAC9g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-10.1,-9.5,20.3,19.1);


(lib.Symbol11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.bottom, null, new cjs.Matrix2D(1,0,0,1,-138.4,-122.7)).s().p("AhXCZIAAkxICvAAIAAExg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-8.8,-15.3,17.6,30.7);


(lib.Symbol10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.bottom, null, new cjs.Matrix2D(1,0,0,1,-24.8,-127.7)).s().p("AhNBmIAAjLICbAAIAADLg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.8,-10.3,15.7,20.6);


(lib.Symbol9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.bottom, null, new cjs.Matrix2D(1,0,0,1,-11.2,-96.8)).s().p("AhuBiIAAjDIDdAAIAADDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-11.2,-9.8,22.4,19.7);


(lib.Symbol8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.bottom, null, new cjs.Matrix2D(1,0,0,1,-16.9,-49.3)).s().p("AioB2IAAjrIFRAAIAADrg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-16.9,-11.8,33.9,23.7);


(lib.Symbol7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.bottom, null, new cjs.Matrix2D(1,0,0,1,-42.3,-10.7)).s().p("AiRBkIAAjHIEjAAIAADHg");
	this.shape.setTransform(0,0.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-14.7,-9.8,29.4,20.2);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.pat, null, new cjs.Matrix2D(1,0,0,1,-74,-74)).s().p("Egi/AbLMAAAg2VMBF/AAAMAAAA2Vg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-224,-174,448,348);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.bot();
	this.instance.setTransform(-39,-133);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-39,-133,79,266);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.logo_b();
	this.instance.setTransform(-114,-66.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-114,-66.5,228,133);


(lib.logo_w_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.logo_w();
	this.instance.setTransform(-104,-59);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-104,-59,208,119);


(lib.blk = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A6PV4MAAAgrvMA0fAAAMAAAArvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,-140,336,280);


(lib.Symbol46 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.t3 = new lib.Symbol49();
	this.t3.setTransform(-20.4,22.2);

	this.t2 = new lib.Symbol48();
	this.t2.setTransform(-8.6,0);

	this.t1 = new lib.Symbol47();
	this.t1.setTransform(0,-22.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.t1},{t:this.t2},{t:this.t3}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-92.9,-36.5,185.9,73);


(lib.Symbol41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.t4 = new lib.Symbol45();
	this.t4.setTransform(0.1,47.3);

	this.t3 = new lib.Symbol44();
	this.t3.setTransform(0.1,15.8);

	this.t2 = new lib.Symbol43();
	this.t2.setTransform(0.1,-15.7);

	this.t1 = new lib.Symbol42();
	this.t1.setTransform(0.1,-47.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.t1},{t:this.t2},{t:this.t3},{t:this.t4}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58.9,-64,118,128);


(lib.Symbol40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol34();
	this.instance.setTransform(-31.5,-7);

	this.instance_1 = new lib.Symbol35();
	this.instance_1.setTransform(-20.5,9);

	this.instance_2 = new lib.Symbol36();
	this.instance_2.setTransform(-55.5,14);

	this.instance_3 = new lib.Symbol37();
	this.instance_3.setTransform(12.5,-37);

	this.instance_4 = new lib.Symbol38();
	this.instance_4.setTransform(25.5,23);

	this.instance_5 = new lib.Symbol39();
	this.instance_5.setTransform(2.5,-23);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-73.5,-70,147,140);


(lib.Symbol31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol32();
	this.instance.setTransform(126,8.4);

	this.instance_1 = new lib.Symbol32();
	this.instance_1.setTransform(154,8.4);

	this.instance_2 = new lib.Symbol32();
	this.instance_2.setTransform(182,8.4);

	this.instance_3 = new lib.Symbol32();
	this.instance_3.setTransform(42,8.4);

	this.instance_4 = new lib.Symbol32();
	this.instance_4.setTransform(70,8.4);

	this.instance_5 = new lib.Symbol32();
	this.instance_5.setTransform(98,8.4);

	this.instance_6 = new lib.Symbol32();
	this.instance_6.setTransform(-182,8.4);

	this.instance_7 = new lib.Symbol32();
	this.instance_7.setTransform(-154,8.4);

	this.instance_8 = new lib.Symbol32();
	this.instance_8.setTransform(-126,8.4);

	this.instance_9 = new lib.Symbol32();
	this.instance_9.setTransform(-98,8.4);

	this.instance_10 = new lib.Symbol32();
	this.instance_10.setTransform(-70,8.4);

	this.instance_11 = new lib.Symbol32();
	this.instance_11.setTransform(-42,8.4);

	this.instance_12 = new lib.Symbol32();
	this.instance_12.setTransform(-14,8.4);

	this.instance_13 = new lib.Symbol32();
	this.instance_13.setTransform(14,8.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_13},{t:this.instance_12},{t:this.instance_11},{t:this.instance_10},{t:this.instance_9},{t:this.instance_8},{t:this.instance_7},{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-196,0,393.5,249.3);


(lib.Symbol30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol29();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,-140,336,280);


(lib.Symbol28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol26();
	this.instance.setTransform(-30.8,5.3);

	this.instance_1 = new lib.Symbol25();
	this.instance_1.setTransform(-31.7,-22.8);

	this.instance_2 = new lib.Symbol24();
	this.instance_2.setTransform(-24.5,22.6);

	this.instance_3 = new lib.Symbol23();
	this.instance_3.setTransform(8.2,13.2);

	this.instance_4 = new lib.Symbol22();
	this.instance_4.setTransform(31.3,-13.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-37,-26.7,74,53.4);


(lib.Symbol21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol18();
	this.instance.setTransform(-64.1,-45.1);

	this.instance_1 = new lib.Symbol17();
	this.instance_1.setTransform(1.8,-41.1);

	this.instance_2 = new lib.Symbol16();
	this.instance_2.setTransform(-19.3,-44.3);

	this.instance_3 = new lib.Symbol15();
	this.instance_3.setTransform(25.5,-41.8);

	this.instance_4 = new lib.Symbol14();
	this.instance_4.setTransform(48.5,-57.4);

	this.instance_5 = new lib.Symbol13();
	this.instance_5.setTransform(63.3,-18);

	this.instance_6 = new lib.Symbol12();
	this.instance_6.setTransform(66.4,26);

	this.instance_7 = new lib.Symbol11();
	this.instance_7.setTransform(61.9,53.4);

	this.instance_8 = new lib.Symbol10();
	this.instance_8.setTransform(-51.7,58.4);

	this.instance_9 = new lib.Symbol9();
	this.instance_9.setTransform(-65.3,27.6);

	this.instance_10 = new lib.Symbol8();
	this.instance_10.setTransform(-59.5,-19.9);

	this.instance_11 = new lib.Symbol7();
	this.instance_11.setTransform(-34.1,-58.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_11},{t:this.instance_10},{t:this.instance_9},{t:this.instance_8},{t:this.instance_7},{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-76.5,-68.7,153,137.4);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.parts = new lib.Symbol28();
	this.parts.setTransform(0,26.3);

	this.timeline.addTween(cjs.Tween.get(this.parts).wait(1));

	// Layer 2
	this.mc = new lib.Symbol27();
	this.mc.setTransform(-2,-3.5);

	this.timeline.addTween(cjs.Tween.get(this.mc).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-37,-53,74,106);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.parts = new lib.Symbol21();
	this.parts.setTransform(0.5,0.3);

	this.timeline.addTween(cjs.Tween.get(this.parts).wait(1));

	// Layer 2
	this.mc = new lib.Symbol20();
	this.mc.setTransform(7.2,18.8);

	this.timeline.addTween(cjs.Tween.get(this.mc).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-76,-68.4,153,137.4);


(lib.logo_b_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.mc = new lib.Symbol1();
	this.mc.setTransform(0.5,0.5,1,1,0,0,0,8.5,0);

	this.timeline.addTween(cjs.Tween.get(this.mc).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-122,-66,228,133);


(lib.head_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// head.png
	this.mc = new lib.Symbol33();

	this.timeline.addTween(cjs.Tween.get(this.mc).wait(1));

	// h1.png
	this.parts = new lib.Symbol40();
	this.parts.setTransform(0.5,-108);

	this.timeline.addTween(cjs.Tween.get(this.parts).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-79,-178,158,261);


(lib.bottle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.mc2 = new lib.Symbol6();
	this.mc2.setTransform(3,-83);

	this.timeline.addTween(cjs.Tween.get(this.mc2).wait(1));

	// Layer 1
	this.mc1 = new lib.Symbol4();
	this.mc1.setTransform(-1,64);

	this.timeline.addTween(cjs.Tween.get(this.mc1).wait(1));

	// Layer 2
	this.bot = new lib.Symbol2();

	this.timeline.addTween(cjs.Tween.get(this.bot).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-77,-136,153,269);


(lib.sc2 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// txt2
	this.txt2 = new lib.Symbol46();
	this.txt2.setTransform(-68.9,101.2);

	this.timeline.addTween(cjs.Tween.get(this.txt2).wait(1));

	// btn
	this.btn = new lib.Symbol50();
	this.btn.setTransform(93,101);

	this.timeline.addTween(cjs.Tween.get(this.btn).wait(1));

	// uz
	this.uz1 = new lib.Symbol31();
	this.uz1.setTransform(0,-124,1,1,180);

	this.uz2 = new lib.Symbol31();
	this.uz2.setTransform(0,124);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.uz2},{t:this.uz1}]}).wait(1));

	// logo_w
	this.logo_w = new lib.logo_w_1();
	this.logo_w.setTransform(56,-30);
	this.logo_w.alpha = 0.5;

	this.timeline.addTween(cjs.Tween.get(this.logo_w).wait(1));

	// txt
	this.txt = new lib.Symbol41();
	this.txt.setTransform(80.1,3.5);

	this.timeline.addTween(cjs.Tween.get(this.txt).wait(1));

	// head
	this.head = new lib.head_1();
	this.head.setTransform(-74,56);

	this.timeline.addTween(cjs.Tween.get(this.head).wait(1));

	// bg
	this.bg = new lib.Symbol30();

	this.timeline.addTween(cjs.Tween.get(this.bg).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-197.5,-373.3,395,746.6);


(lib.content = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		var r = this;
		var count = 1;
		var repeat = 2;
		var time2 = 5.0;
		var time3 = time2+3.0;
		var time4 = time3+3.0;
		
		var dlit = 0.15
		var del = 0.15
		var ease = Power0.easeNone
		//var ease = Sine.easeIn
		//wings
		//TweenMax.to(r.birdCont.bird1.w1, dlit, {rotation:"-=60", scaleY:0.5, yoyo:true, repeat:-1, repeatDelay:0.0, ease:ease}, 0.0)
		//TweenMax.to(r.birdCont.bird1.w1.w2, dlit, {rotation:"-=50", scaleY:0.3, yoyo:true, repeat:-1, repeatDelay:0.0, ease:ease}, del)
		TweenMax.to(r.sc2.uz1, 0.9, {x:"-=29", yoyo:false, repeat:-1, repeatDelay:0.0, ease:ease}, 0.0)
		TweenMax.to(r.sc2.uz2, 0.9, {x:"+=29", yoyo:false, repeat:-1, repeatDelay:0.0, ease:ease}, 0.0)
		
		
		var tl = new TimelineLite();
		tl.fromTo(r.blk, 0.5, {alpha:1}, {alpha:0, ease:Power0.easeNone})
		  .from(r.logo_b, 1.0, {/*x:"-=350", y:"-=550", */scaleX:3, scaleY:3, ease:Expo.easeOut}, 0.0)
		  .from(r.logo_b.mc, 3.0, {/*x:"-=350", y:"-=550", */scaleX:1.1, scaleY:1.1, ease:Power0.easeNone}, 0.0)
		  //.from(r.birdCont.bird1.tail, 1.5, {scaleY:0.3, ease:Expo.easeOut}, 2.0)
		  .to(r.logo_b.mc, 1.0, {x:105, y:-97, scaleX:0.5, scaleY:0.5, ease:Expo.easeInOut}, 2.0)
		  
		  //2
		  .from(r.bot.bot, 0.8, {y:"+=350", ease:Expo.easeOut}, 2.5)
		  .from(r.bot.mc1, 0.8, {y:"+=350", alpha:0, ease:Expo.easeOut}, 2.7)
		  .from(r.bot.mc2, 0.8, {y:"-=350", alpha:0, ease:Expo.easeOut}, 2.7)
		  
		  //3
		  .from(r.sc2.bg, 1.0, {scaleX:3, scaleY:3, alpha:0, ease:Expo.easeOut}, time2)
		  .from(r.sc2.uz1, 1.0, {y:"-=50", ease:Expo.easeOut}, time2+0.50)
		  .from(r.sc2.uz2, 1.0, {y:"+=50", ease:Expo.easeOut}, time2+0.50)
		  
		  .from(r.sc2.head, 1.0, {y:"+=350", ease:Expo.easeOut}, time2+0.50)
		  .staggerFrom([r.sc2.txt.t1, r.sc2.txt.t2, r.sc2.txt.t3, r.sc2.txt.t4], 1.0, {x:"+=300", ease:Expo.easeOut}, 0.1, time2+1.0)
		  
		  
		  //4
		  .staggerTo([r.sc2.txt.t1, r.sc2.txt.t2, r.sc2.txt.t3, r.sc2.txt.t4], 1.0, {y:"-=300", ease:Expo.easeInOut}, 0.03, time2+3.0)
		  .to(r.sc2.uz2, 1.0, {y:"-=73", ease:Expo.easeInOut}, time2+3.10)
		  .to(r.sc2.head, 1.0, {x:"-=20", y:"-=50", scaleX:0.75, scaleY:0.75, ease:Expo.easeInOut}, time2+3.10)
		  .from(r.sc2.logo_w, 1.6, {y:"+=350", ease:Expo.easeInOut}, time2+3.40)
		  .staggerFrom([r.sc2.txt2.t1, r.sc2.txt2.t2, r.sc2.txt2.t3], 1.0, {y:"+=300", ease:Expo.easeOut}, 0.1, time2+3.6)
		  .from(r.sc2.btn, 1.5, {scaleX:0, scaleY:0, ease:Elastic.easeOut}, time2+3.9)
		  
		  
		  //.staggerTo([r.t3.t3, r.t3.t2, r.t3.t1], 0.8, {y:"+=430", ease:Expo.easeIn}, 0.1, time2)
		  //
		
		
		  
		  .call(replay)
		  .to(r.blk, 0.6, {alpha:1, ease:Power0.easeNone, onComplete:restart}, 18)
		  ;
		
		tl.duration(15);
		  
		
		function replay() {
		  if (count == repeat){
		      tl.pause();
			  //console.log(321);
			  TweenMax.killAll();
		  } else {
		  if (count != repeat) {
			  count++;
			  tl.play();
		  }
		  }
		}
		
		
		function restart() {
			tl.play(0);
		}
		
		TweenMax.to(r.allStop, 29.8, {x:1000, onComplete:check})
		function check() {
			//console.log(123);
			//TweenMax.killAll();
		}
		
		var z = r.bot.mc1.parts;
		function partsTop() {
			var i = 0;
			for (currObj in z) {
			  if(z[currObj] && typeof z[currObj] == "object" && i>=56){
				  TweenMax.from(z[currObj], 1.2, {x:0, y:100, scaleX:0, scaleY:0, rotation:"+=380", alpha:0, ease:Expo.easeOut, delay:(56-i)*0.025+2.5});
				  }
			i++;
			 }
		}
		partsTop();
		
		var zz = r.bot.mc2.parts;
		function parts2Top() {
			var i = 0;
			for (currObj in zz) {
			  if(zz[currObj] && typeof zz[currObj] == "object" && i>=56){
				  TweenMax.from(zz[currObj], 1.2, {x:0, y:-100, scaleX:0, scaleY:0, rotation:"+=380", alpha:0, ease:Expo.easeOut, delay:(56-i)*0.025+2.5});
				  }
			i++;
			 }
		}
		parts2Top();
		
		
		var zzz = r.sc2.head.parts;
		function head() {
			var i = 0;
			for (currObj in zzz) {
			  if(zzz[currObj] && typeof zzz[currObj] == "object" && i>=56){
				  TweenMax.from(zzz[currObj], 1.8, {y:"+=100", scaleX:0, scaleY:0, alpha:0, ease:Elastic.easeOut, delay:(56-i)*0.075+5.0});
				  }
			i++;
			 }
		}
		head();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Layer 6
	this.allStop = new lib.Symbol19();
	this.allStop.setTransform(312.5,285);

	this.timeline.addTween(cjs.Tween.get(this.allStop).wait(1));

	// blk
	this.blk = new lib.blk();

	this.timeline.addTween(cjs.Tween.get(this.blk).wait(1));

	// sc2
	this.sc2 = new lib.sc2();

	this.timeline.addTween(cjs.Tween.get(this.sc2).wait(1));

	// bot
	this.bot = new lib.bottle();
	this.bot.setTransform(-1,7);

	this.timeline.addTween(cjs.Tween.get(this.bot).wait(1));

	// logo_b
	this.logo_b = new lib.logo_b_1();

	this.timeline.addTween(cjs.Tween.get(this.logo_b).wait(1));

	// bg_pattern
	this.instance = new lib.Symbol5();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-224,-373.3,541.5,746.6);


// stage content:
(lib.al_336x280 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A6PV3MAAAgrtMA0fAAAMAAAArtg");
	mask.setTransform(168,140);

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("rgba(0,0,0,0.098)").ss(2,1,1).p("A6P13MA0fAAAMAAAArvMg0fAAAg");
	this.shape.setTransform(168,140);

	this.shape.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// movie
	this.rolik = new lib.content();
	this.rolik.setTransform(168,140);

	this.rolik.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.rolik).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(168,140,336,280);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;